description = "A simple colorful theme for Hugo."
features = ["blog", "shortcode", "syntax Highlighting"]
homepage = "https://github.com/vendelin8/hugo-theme-hello-tricolor/"
license = "MIT"
licenselink = "https://github.com/vendelin8/hugo-theme-hello-tricolor/blob/master/LICENSE.md"
min_version = 0.74
name = "hello-tricolor"
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "light",
  "minimal",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
]

[author]
  homepage = "https://vendelin.ml"
  name = "vendelin8"

[original]
  author =  "panr"
  homepage = "https://radoslawkoziel.pl"
  repo = "https://github.com/panr/hugo-theme-hello-friend"
